// actionTypes.js
export const CREATE_REWARD_REQUEST = 'CREATE_REWARD_REQUEST';
export const CREATE_REWARD_SUCCESS = 'CREATE_REWARD_SUCCESS';
export const CREATE_REWARD_FAILURE = 'CREATE_REWARD_FAILURE';

export const UPDATE_REWARD_REQUEST = 'UPDATE_REWARD_REQUEST';
export const UPDATE_REWARD_SUCCESS = 'UPDATE_REWARD_SUCCESS';
export const UPDATE_REWARD_FAILURE = 'UPDATE_REWARD_FAILURE';

export const GET_REWARD_REQUEST = 'GET_REWARD_REQUEST';
export const GET_REWARD_SUCCESS = 'GET_REWARD_SUCCESS';
export const GET_REWARD_FAILURE = 'GET_REWARD_FAILURE';

export const GET_ALL_REWARDS_REQUEST = 'GET_ALL_REWARDS_REQUEST';
export const GET_ALL_REWARDS_SUCCESS = 'GET_ALL_REWARDS_SUCCESS';
export const GET_ALL_REWARDS_FAILURE = 'GET_ALL_REWARDS_FAILURE';
